# .goreleaser.yml
builds:
- main: cmd/orca.go
  binary: orca
  goos:
  - linux
  goarch:
  - amd64
  env:
  - CGO_ENABLED=0
  ldflags:
  - -s -w -X main.GitTag={{.Tag}} -X main.GitCommit={{.ShortCommit}}

archives:
  - 
    id: orca
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}"
    format: tar.gz
    wrap_in_directory: true

dockers:
  - 
    binaries: 
      - orca
    dockerfile: Dockerfile
    image_templates:
    - "nuvo/{{.ProjectName}}:{{ .Tag }}"
    - "nuvo/{{.ProjectName}}:latest"
