[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "gopkg.in/src-d/go-git.v4"
  version = "4.6.0"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.1"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.13.2"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.13.2"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.13.2"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true
